import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  engineering: [
    {
      type: 'category',
      label: 'Understand the system',
      collapsed: false,
      items: [
        'index',
        'system-map',
        'glossary',
        {type: 'link', label: 'Bounded-context map', href: '/project/CONTEXT-MAP'},
      ],
    },
    {
      type: 'category',
      label: 'Explore the zones',
      items: [
        'architecture/edge-runtime',
        'architecture/governance-gateway',
        'architecture/enterprise-intelligence-and-resources',
      ],
    },
    {
      type: 'category',
      label: 'Follow a request',
      items: [
        'flows/governed-request',
        'flows/confirmation',
        'flows/reasoning-escalation',
        'fastmcp-apps-and-prefab-overlay',
      ],
    },
    {
      type: 'category',
      label: 'Experiences and deployments',
      items: [
        'experiences/client-landscape',
        'architecture/use-cases-and-deployments',
        'deployment-topology',
        'demos/nhs-care',
        'demos/northstar-infrastructure-operations',
      ],
    },
    {
      type: 'category',
      label: 'Build and extend',
      items: [
        'how-to/add-edge-experience',
        'how-to/author-integration-definition',
        'how-to/enable-reasoning-tools',
        'how-to/build-fastmcp-app',
        'how-it-works/snapshot-lifecycle',
      ],
    },
    {
      type: 'category',
      label: 'Contracts and decisions',
      items: ['data-boundary-and-projection-contract', {type: 'autogenerated', dirName: 'adr'}],
    },
    {
      type: 'category',
      label: 'Operate and demonstrate',
      items: [
        'dev/local-demo-runbook',
        'keycloak-auth-testing',
        'reference/evidence-and-maturity',
        'graphs/README',
      ],
    },
    {
      type: 'category',
      label: 'Research and history',
      items: [
        'dev/governed-apps-reference-examples-development-plan',
        'dev/projection-boundary-documentation-audit',
        'research/langgraph-fastmcp-react-patterns',
      ],
    },
  ],
};

export default sidebars;
